### ISSUE TITLE
All meshes show up as checkered box. Missing Resource of Type 'ezMeshResource'

### ISSUE THREAD

**Issue by antonyjones67** [ez-engines/ez-settings#21]
Just pulled up one of the samples in the editor. I am getting the warning. Missing Resource of Type 'ezMeshResource':. In Asteroid for instance.

Windows 10
NVIDIA 1060 gtx

Master Branch.
At hash e4d783469d6a3798e6bb91670f2163e959f37a2b
.

**Comment by sveredyuk** [comment]
@antonyjones67 Hi, I really don't understand what about you saying. Sorry )

**Comment by antonyjones67** [comment]
Sorry. I watched your video and realized I needed to click on the gear in the bottom right corner of the asset in the content browser. To load the resource. My mistake.

**Comment by antonyjones67** [comment]
My bad i am in the wrong repository. Sorry.
